### ISSUE TITLE
[Bug]: Can't lunch Scrapper

### ISSUE THREAD

**Issue by Ozer0x777** [RansomLook/RansomLook#169]
### What happened?

I can't start scraping (telegram too) I always get the same errors are they missing dependencies?

I am using ubuntu 22 as recommended.

### Relevant log output

```shell
2023-06-08:13:09:33,144 ERROR    Executable doesn't exist at /root/.cache/ms-playwright/chromium-1060/chrome-linux/chrome
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
2023-06-08:13:09:33,145 ERROR    error
Exception in thread Thread-3 (threadscape):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/RansomLook/ransomlook/ransomlook.py", line 105, in threadscape
    browser.close()
UnboundLocalError: local variable 'browser' referenced before assignment
Exception in thread Thread-1 (threadscape):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
Exception in thread Thread-4 (threadscape):
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/root/RansomLook/ransomlook/ransomlook.py", line 105, in threadscape
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/RansomLook/ransomlook/ransomlook.py", line 105, in threadscape
    browser.close()
UnboundLocalError: local variable 'browser' referenced before assignment
    browser.close()
UnboundLocalError: local variable 'browser' referenced before assignment
Exception in thread Thread-2 (threadscape):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/RansomLook/ransomlook/ransomlook.py", line 105, in threadscape
    browser.close()
UnboundLocalError: local variable 'browser' referenced before assignment
```

**Comment by Rafiot** [comment]
You should try to run `playwright install`, as the error message invites you to.

Make sure you run it from the poetry environment, that should be `poetry run playwright install` from the RansomLook directory.

**Comment by FafnerKeyZee** [comment]
Hey,

Looking a the message it seems that playwright isn't correctly installed as mentionned by @Rafiot .
Did you run the last step of installation:
poetry run update
?

BR

**Comment by FafnerKeyZee** [comment]
Oopsie will be fixed for next push ;)
